Added dutch translations for keycloak 12
antek-drzewiecki/keycloak pull request #1
Opened 2021-02-16 11:42 UTC by antek-drzewiecki

Since Redhat SSO is not properly working. I was not able to see the JIRA board and find a ticket for this issue.

This pull requests adds translations for the community edition of keycloak. All except for WebAuthn since I can't reproduce the flows.

2021-02-16 12:28 UTC, fndejong requested changes

2021-02-16 12:28 UTC, fndejong commented on themes/src/main/resources-community/theme/base/login/messages/messages_nl.properties
> +deletingAccountForbidden=U heeft onvoldoende permissies om de account te verwijderen
het account

2021-02-16 12:28 UTC, fndejong commented on themes/src/main/resources-community/theme/base/login/messages/messages_nl.properties
> +saml.post-form.message=U wordt verwezen, een moment geduld alstublief.
doorverwezen?

alstublieft*

2021-02-16 12:28 UTC, fndejong commented on themes/src/main/resources-community/theme/base/login/messages/messages_nl.properties
> +openshift.scope.user_check-access=Gebruikers toegang informatie
in theorie zou dit 1 woord zijn

2021-02-16 12:32 UTC, TriMM-Berend commented on themes/src/main/resources-community/theme/base/login/messages/messages_nl.properties
> +credentialSetupRequired=Kan niet inloggen, aanmeldgegeven moeten worden geconfigureerd.
Aanmeldgegevens*

2021-02-17 09:38 UTC, fndejong commented on themes/src/main/resources-community/theme/base/login/messages/messages_nl.properties
>  loginTotpStep1=Installeer een van de volgende applicaties op uw mobile telefoon
mobiele* telefoon (zie ik net tijdens de demo)

2021-02-17 09:38 UTC, fndejong commented on themes/src/main/resources-community/theme/base/login/messages/messages_nl.properties
> +loginChooseAuthenticator=Selecteer een login methode
inlogmethode (denk ik)

2021-02-17 09:39 UTC, fndejong commented on themes/src/main/resources-community/theme/base/login/messages/messages_nl.properties
> +invalidUsernameMessage=Ongeldig gebruikersnaam.
Ongeldige*

2021-07-13 11:27 UTC, closed without merging